### ISSUE TITLE
can't disable focuspoints for non-images

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-responsive-images-plugin#116]
Hello.
OCMS 3.7.5. responsive-images 2.8
I can't disable focuspoints for non-images.
'focuspoint: false' seems to have no effect.

```
pdf:
        label: PDF
        span: auto
        mode: file
        type: fileupload
        fileTypes: pdf
        mimeTypes: application/pdf
        focuspoint: false
```
